[workspace]
members = [
    "crates/auralis-signal",
    "crates/auralis-task",
    "crates/auralis-devtools",
]
resolver = "2"

[workspace.package]
version = "0.1.18"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/chh-itt/auralis"
rust-version = "1.80"

[workspace.dependencies]
# Internal
auralis-signal  = { path = "crates/auralis-signal", version = "0.1.18" }
auralis-task    = { path = "crates/auralis-task", version = "0.1.18" }
auralis-devtools = { path = "crates/auralis-devtools", version = "0.1.18" }

[profile.release]
opt-level     = "s"
lto           = true
codegen-units = 1
strip         = true

[profile.dev]
opt-level = 0
